---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Managed Prometheus
      type: prometheus
      url: {{ws_url}}
      jsonData:
        sigV4Auth: true
        sigV4Region: us-east-1
        sigV4AuthType: default
